/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Ventanas;

import InicioSesion.InicioSesion;

/**
 *
 * @author erick
 */
public class VentAgregarClub extends javax.swing.JFrame {

    /**
     * Creates new form ventAgregarClub
     */
    public VentAgregarClub() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelClub = new javax.swing.JPanel();
        panelLogo = new javax.swing.JPanel();
        iconoClub = new javax.swing.JLabel();
        etiquetaTorneo = new javax.swing.JLabel();
        etiquetaMenuIngresoClub = new javax.swing.JLabel();
        encabezadoClub = new javax.swing.JLabel();
        boton = new javax.swing.JButton();
        etiqueta = new javax.swing.JLabel();
        botonCerrar = new javax.swing.JButton();
        botonMinimizar = new javax.swing.JButton();
        botonSesion = new javax.swing.JButton();
        etiquetaCodClub = new javax.swing.JLabel();
        cajaCodClub = new javax.swing.JTextField();
        etiquetaNomClub = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        etiquetaNomClub1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        etiquetaNomClub2 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        etiquetaNomClub3 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        etiquetaNomClub4 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        jComboBox1 = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panelClub.setBackground(new java.awt.Color(255, 255, 255));

        panelLogo.setBackground(new java.awt.Color(0, 51, 102));

        iconoClub.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        iconoClub.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/logoClub.png"))); // NOI18N

        etiquetaTorneo.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        etiquetaTorneo.setForeground(new java.awt.Color(255, 255, 255));
        etiquetaTorneo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        etiquetaTorneo.setText("LIGA DE FÚTBOL");

        etiquetaMenuIngresoClub.setFont(new java.awt.Font("Segoe UI", 0, 22)); // NOI18N
        etiquetaMenuIngresoClub.setForeground(new java.awt.Color(255, 153, 0));
        etiquetaMenuIngresoClub.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        etiquetaMenuIngresoClub.setText("Menú Ingreso Club");

        javax.swing.GroupLayout panelLogoLayout = new javax.swing.GroupLayout(panelLogo);
        panelLogo.setLayout(panelLogoLayout);
        panelLogoLayout.setHorizontalGroup(
            panelLogoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(etiquetaTorneo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(panelLogoLayout.createSequentialGroup()
                .addGroup(panelLogoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelLogoLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(etiquetaMenuIngresoClub, javax.swing.GroupLayout.DEFAULT_SIZE, 224, Short.MAX_VALUE))
                    .addGroup(panelLogoLayout.createSequentialGroup()
                        .addGap(54, 54, 54)
                        .addComponent(iconoClub)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        panelLogoLayout.setVerticalGroup(
            panelLogoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLogoLayout.createSequentialGroup()
                .addGap(90, 90, 90)
                .addComponent(iconoClub)
                .addGap(30, 30, 30)
                .addComponent(etiquetaMenuIngresoClub)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(etiquetaTorneo, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        encabezadoClub.setFont(new java.awt.Font("Segoe UI", 0, 22)); // NOI18N
        encabezadoClub.setForeground(new java.awt.Color(255, 153, 0));
        encabezadoClub.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        encabezadoClub.setText("Ingreso de Club");

        boton.setBackground(new java.awt.Color(255, 255, 255));
        boton.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        boton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/logoConfirmar.png"))); // NOI18N
        boton.setToolTipText("");
        boton.setBorder(null);
        boton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonActionPerformed(evt);
            }
        });

        etiqueta.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        etiqueta.setForeground(new java.awt.Color(102, 102, 102));
        etiqueta.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        etiqueta.setText("REGISTRAR");

        botonCerrar.setBackground(new java.awt.Color(255, 255, 255));
        botonCerrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/botonCerrar.png"))); // NOI18N
        botonCerrar.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        botonCerrar.setFocusable(false);
        botonCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCerrarActionPerformed(evt);
            }
        });

        botonMinimizar.setBackground(new java.awt.Color(255, 255, 255));
        botonMinimizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/botonMinimzar.png"))); // NOI18N
        botonMinimizar.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        botonMinimizar.setFocusable(false);
        botonMinimizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonMinimizarActionPerformed(evt);
            }
        });

        botonSesion.setBackground(new java.awt.Color(255, 255, 255));
        botonSesion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/botonSesion.png"))); // NOI18N
        botonSesion.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        botonSesion.setFocusable(false);
        botonSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonSesionActionPerformed(evt);
            }
        });

        etiquetaCodClub.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        etiquetaCodClub.setForeground(new java.awt.Color(102, 102, 102));
        etiquetaCodClub.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        etiquetaCodClub.setText("CODIGO CLUB");

        cajaCodClub.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cajaCodClubActionPerformed(evt);
            }
        });

        etiquetaNomClub.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        etiquetaNomClub.setForeground(new java.awt.Color(102, 102, 102));
        etiquetaNomClub.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        etiquetaNomClub.setText("¿DESEA AGREGAR ALGÚN CARGO ADMINISTRATIVO?");

        etiquetaNomClub1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        etiquetaNomClub1.setForeground(new java.awt.Color(102, 102, 102));
        etiquetaNomClub1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        etiquetaNomClub1.setText("NOMBRE CLUB");

        etiquetaNomClub2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        etiquetaNomClub2.setForeground(new java.awt.Color(102, 102, 102));
        etiquetaNomClub2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        etiquetaNomClub2.setText("AFORO");

        etiquetaNomClub3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        etiquetaNomClub3.setForeground(new java.awt.Color(102, 102, 102));
        etiquetaNomClub3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        etiquetaNomClub3.setText("LOCALIZACIÓN");

        etiquetaNomClub4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        etiquetaNomClub4.setForeground(new java.awt.Color(102, 102, 102));
        etiquetaNomClub4.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        etiquetaNomClub4.setText("NOMBRE ESTADIO");

        jTextField4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField4ActionPerformed(evt);
            }
        });

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jButton1.setText("SÍ");

        jButton2.setText("NO");

        javax.swing.GroupLayout panelClubLayout = new javax.swing.GroupLayout(panelClub);
        panelClub.setLayout(panelClubLayout);
        panelClubLayout.setHorizontalGroup(
            panelClubLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelClubLayout.createSequentialGroup()
                .addComponent(panelLogo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(panelClubLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelClubLayout.createSequentialGroup()
                        .addGap(197, 197, 197)
                        .addComponent(jButton1)
                        .addGap(38, 38, 38)
                        .addComponent(jButton2))
                    .addGroup(panelClubLayout.createSequentialGroup()
                        .addGap(72, 72, 72)
                        .addGroup(panelClubLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jSeparator1)
                            .addGroup(panelClubLayout.createSequentialGroup()
                                .addGroup(panelClubLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(etiquetaNomClub1, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(etiquetaCodClub, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(etiquetaNomClub3, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(panelClubLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextField3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextField1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cajaCodClub, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(panelClubLayout.createSequentialGroup()
                                .addGroup(panelClubLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(etiquetaNomClub4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(etiquetaNomClub2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(63, 63, 63)
                                .addGroup(panelClubLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jTextField4, javax.swing.GroupLayout.DEFAULT_SIZE, 264, Short.MAX_VALUE)
                                    .addComponent(jTextField2)))
                            .addComponent(jSeparator2, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(encabezadoClub, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 431, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(panelClubLayout.createSequentialGroup()
                        .addGap(101, 101, 101)
                        .addGroup(panelClubLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jComboBox1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(etiquetaNomClub, javax.swing.GroupLayout.DEFAULT_SIZE, 325, Short.MAX_VALUE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE)
                .addGroup(panelClubLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelClubLayout.createSequentialGroup()
                        .addComponent(botonSesion)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(botonMinimizar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(botonCerrar)
                        .addGap(45, 45, 45))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelClubLayout.createSequentialGroup()
                        .addGroup(panelClubLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(boton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(etiqueta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(48, 48, 48))))
        );
        panelClubLayout.setVerticalGroup(
            panelClubLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelLogo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(panelClubLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelClubLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(botonCerrar)
                    .addComponent(botonMinimizar)
                    .addComponent(botonSesion))
                .addGroup(panelClubLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelClubLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(encabezadoClub)
                        .addGap(29, 29, 29)
                        .addGroup(panelClubLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(etiquetaCodClub)
                            .addComponent(cajaCodClub, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(panelClubLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(etiquetaNomClub1)
                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(panelClubLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(etiquetaNomClub3)
                            .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(21, 21, 21)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(panelClubLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(etiquetaNomClub4))
                        .addGap(18, 18, 18)
                        .addGroup(panelClubLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(etiquetaNomClub2)
                            .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(etiquetaNomClub)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panelClubLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton2)
                            .addComponent(jButton1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelClubLayout.createSequentialGroup()
                        .addGap(302, 302, 302)
                        .addComponent(boton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(etiqueta)))
                .addGap(0, 20, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelClub, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelClub, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonActionPerformed
        Principal pPrincipal = new Principal();
        pPrincipal.setVisible(true);
        dispose();
    }//GEN-LAST:event_botonActionPerformed

    private void botonCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCerrarActionPerformed
        System.exit(0);
    }//GEN-LAST:event_botonCerrarActionPerformed

    private void botonMinimizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonMinimizarActionPerformed
        this.setExtendedState(1);
    }//GEN-LAST:event_botonMinimizarActionPerformed

    private void botonSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonSesionActionPerformed
        InicioSesion pInicio = new InicioSesion();
        pInicio.setVisible(true);
        dispose();
    }//GEN-LAST:event_botonSesionActionPerformed

    private void cajaCodClubActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cajaCodClubActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cajaCodClubActionPerformed

    private void jTextField4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentAgregarClub.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentAgregarClub.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentAgregarClub.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentAgregarClub.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentAgregarClub().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton boton;
    private javax.swing.JButton botonCerrar;
    private javax.swing.JButton botonMinimizar;
    private javax.swing.JButton botonSesion;
    private javax.swing.JTextField cajaCodClub;
    private javax.swing.JLabel encabezadoClub;
    private javax.swing.JLabel etiqueta;
    private javax.swing.JLabel etiquetaCodClub;
    private javax.swing.JLabel etiquetaMenuIngresoClub;
    private javax.swing.JLabel etiquetaNomClub;
    private javax.swing.JLabel etiquetaNomClub1;
    private javax.swing.JLabel etiquetaNomClub2;
    private javax.swing.JLabel etiquetaNomClub3;
    private javax.swing.JLabel etiquetaNomClub4;
    private javax.swing.JLabel etiquetaTorneo;
    private javax.swing.JLabel iconoClub;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JPanel panelClub;
    private javax.swing.JPanel panelLogo;
    // End of variables declaration//GEN-END:variables
}
